# Generated by Django 4.2 on 2025-07-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0009_alter_comment_text'),
        ('users', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='read_poems',
            field=models.ManyToManyField(related_name='read_poems', to='show.poem'),
        ),
    ]
