# Generated by Django 4.2 on 2025-07-08 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0002_poem_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='poems', to=settings.AUTH_USER_MODEL),
        ),
    ]
