# Generated by Django 4.2 on 2025-07-09 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePoem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_poems', to='show.poem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_poems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'poem')},
            },
        ),
    ]
