# Generated by Django 4.2 on 2025-07-09 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0005_savepoem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savepoem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poem',
            name='reads',
            field=models.ManyToManyField(related_name='reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
