# Generated by Django 4.2 on 2025-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_alter_savepoem_unique_together_poem_reads'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bad_words', models.JSONField(default=list)),
            ],
        ),
    ]
