# Generated by Django 4.2 on 2025-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_badwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badwords',
            name='bad_words',
            field=models.CharField(max_length=120),
        ),
    ]
